version: '3.9'

services:
  api:
    container_name: miliano-ewallet-api
    image: miliano-ewallet-api:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    ports:
      - '6000:3000'
    networks:
      - miliano-ewallet-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - database

  database:
    container_name: miliano-ewallet-database
    image: postgres:12
    env_file: .env
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_LOCAL_PORT
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - miliano-ewallet-network
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  miliano-ewallet-network:

volumes:
  postgres-data:
